FROM alpine:3.15

RUN apk add --no-cache \
    rutorrent \
    lighttpd \
    php7 \
    php7-cgi \
    php7-json \
    --

RUN addgroup lighttpd rutorrent

CMD lighttpd -f /etc/lighttpd/lighttpd.conf -D
